# Generated by Django 6.1.1 on 2026-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        choices=[("Sales", "Sales"), ("IT", "IT"), ("HR", "HR")],
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitCommitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_sha", models.CharField(unique=True)),
                ("author_email", models.EmailField(max_length=254)),
                ("commit_date", models.DateTimeField()),
                ("commit_message", models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                (
                    "departments",
                    models.ManyToManyField(blank=True, to="examples.department"),
                ),
            ],
        ),
    ]
