# Generated by Django 6.1.1 on 2026-09-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporting_year_month", models.CharField()),
                ("employee_name", models.CharField()),
                ("department_name", models.CharField()),
                ("number_of_commits", models.IntegerField()),
            ],
            options={
                "managed": False,
            },
        ),
    ]
