# Generated by Django 6.1.1 on 2026-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0002_employeereport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporting_date", models.DateField()),
            ],
            options={
                "db_table": "selection_period_cte",
                "managed": False,
            },
        ),
    ]
